#!/bin/sh
export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 smusheer/12162840@'(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))' <<EOF
DROP TABLE VEIL CASCADE CONSTRAINTS;
DROP TABLE GOWN CASCADE CONSTRAINTS;
DROP TABLE CLIENT CASCADE CONSTRAINTS;
DROP TABLE BUYORDER CASCADE CONSTRAINTS;
DROP TABLE RENTALORDER CASCADE CONSTRAINTS;
DROP TABLE BUYITEMS CASCADE CONSTRAINTS;
DROP TABLE RENTALITEMS CASCADE CONSTRAINTS;
DROP TABLE ALTERATIONS CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
exit;
EOF